INSERT INTO amenities VALUES('AC');
INSERT INTO amenities VALUES('Breakfast');
INSERT INTO amenities VALUES('Dinner');
INSERT INTO amenities VALUES('Elevator');
INSERT INTO amenities VALUES('Fire Place');
INSERT INTO amenities VALUES('Free Parking');
INSERT INTO amenities VALUES('Free Wifi');
INSERT INTO amenities VALUES('Gym');
INSERT INTO amenities VALUES('Hair Dryer');
INSERT INTO amenities VALUES('Hangers');
INSERT INTO amenities VALUES('Heater');
INSERT INTO amenities VALUES('Hot Tub');
INSERT INTO amenities VALUES('Iron');
INSERT INTO amenities VALUES('Kitchen');
INSERT INTO amenities VALUES('Laptop ready');
INSERT INTO amenities VALUES('Lunch');
INSERT INTO amenities VALUES('Merchandise');
INSERT INTO amenities VALUES('Polaroid Camera');
INSERT INTO amenities VALUES('Pool');
INSERT INTO amenities VALUES('TV');
INSERT INTO amenities VALUES('Washing Machine');
INSERT INTO amenities VALUES('Wheelchair accessible');
